version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: sparrowrobotics_web
    restart: always

  nginx:
    image: nginx:latest
    container_name: sparrowrobotics_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web


